export const UPLOAD_TYPE_TRANSLATIONS: Record<string, string> = {
  // English to Spanish translations
  hud: "HUD",
  overlay: "Overlay",
  crosshair: "Mira",
  minimap: "Minimapa",
  ui: "Interfaz de Usuario",
  config: "Configuración",
  preset: "Preset",
  settings: "Configuraciones",
  profile: "Perfil",
  layout: "Diseño",
  theme: "Tema",
  skin: "Skin",
  mod: "Modificación",
  plugin: "Plugin",
  addon: "Complemento",
  script: "Script",
  tutorial: "Tutorial",
  guide: "Guía",
  template: "Plantilla",
  pack: "Paquete",
  collection: "Colección",
  bundle: "Bundle",
  setup: "Setup",
  installation: "Instalación",
  screenshot: "Captura de Pantalla",
  video: "Video",
  stream: "Stream",
  clip: "Clip",
  highlight: "Highlight",
  montage: "Montaje",
  edit: "Edición",
  gameplay: "Gameplay",
  review: "Reseña",
  analysis: "Análisis",
  comparison: "Comparación",
  showcase: "Showcase",
  demo: "Demostración",
  example: "Ejemplo",
  sample: "Muestra",
  test: "Prueba",
  beta: "Beta",
  alpha: "Alpha",
  release: "Lanzamiento",
  update: "Actualización",
  patch: "Parche",
  hotfix: "Hotfix",
  bugfix: "Corrección de Errores",
  enhancement: "Mejora",
  feature: "Característica",
  improvement: "Mejora",
  optimization: "Optimización",
  performance: "Rendimiento",
  fps: "FPS",
  quality: "Calidad",
  resolution: "Resolución",
  graphics: "Gráficos",
  visual: "Visual",
  audio: "Audio",
  sound: "Sonido",
  music: "Música",
  voice: "Voz",
  chat: "Chat",
  communication: "Comunicación",
  social: "Social",
  community: "Comunidad",
  clan: "Clan",
  team: "Equipo",
  guild: "Gremio",
  organization: "Organización",
  tournament: "Torneo",
  competition: "Competencia",
  esports: "Esports",
  professional: "Profesional",
  amateur: "Amateur",
  casual: "Casual",
  hardcore: "Hardcore",
  beginner: "Principiante",
  intermediate: "Intermedio",
  advanced: "Avanzado",
  expert: "Experto",
  master: "Maestro",
  pro: "Pro",
  streamer: "Streamer",
  content: "Contenido",
  creator: "Creador",
  influencer: "Influencer",
  youtuber: "YouTuber",
  twitcher: "Twitcher",
  gamer: "Gamer",
  player: "Jugador",
  user: "Usuario",
  custom: "Personalizado",
  personal: "Personal",
  private: "Privado",
  public: "Público",
  shared: "Compartido",
  official: "Oficial",
  unofficial: "No Oficial",
  fan: "Fan",
  community_made: "Hecho por la Comunidad",
  original: "Original",
  inspired: "Inspirado",
  remix: "Remix",
  variant: "Variante",
  alternative: "Alternativo",
  backup: "Respaldo",
  archive: "Archivo",
  legacy: "Legado",
  classic: "Clásico",
  retro: "Retro",
  vintage: "Vintage",
  modern: "Moderno",
  futuristic: "Futurista",
  minimalist: "Minimalista",
  detailed: "Detallado",
  simple: "Simple",
  complex: "Complejo",
  clean: "Limpio",
  dark: "Oscuro",
  light: "Claro",
  colorful: "Colorido",
  monochrome: "Monocromático",
  neon: "Neón",
  glowing: "Brillante",
  transparent: "Transparente",
  opaque: "Opaco",
  animated: "Animado",
  static: "Estático",
  dynamic: "Dinámico",
  interactive: "Interactivo",
  responsive: "Responsivo",
  adaptive: "Adaptativo",
  smart: "Inteligente",
  auto: "Automático",
  manual: "Manual",
  fixed: "Fijo",
  movable: "Movible",
  resizable: "Redimensionable",
  scalable: "Escalable",
  flexible: "Flexible",
  rigid: "Rígido",
  stable: "Estable",
  experimental: "Experimental",
};

/**
 * Traduce un tipo de upload del inglés al español
 * @param type - El tipo de upload en inglés
 * @returns El tipo traducido al español o el tipo original si no hay traducción
 */
export function translateUploadType(type: string): string {
  const normalizedType = type.toLowerCase().trim();
  return UPLOAD_TYPE_TRANSLATIONS[normalizedType] || type;
}

/**
 * Verifica si un tipo de upload tiene traducción disponible
 * @param type - El tipo de upload a verificar
 * @returns true si hay traducción disponible, false en caso contrario
 */
export function hasTranslation(type: string): boolean {
  const normalizedType = type.toLowerCase().trim();
  return normalizedType in UPLOAD_TYPE_TRANSLATIONS;
}

/**
 * Obtiene todas las traducciones disponibles
 * @returns Un objeto con todas las traducciones disponibles
 */
export function getAllTranslations(): Record<string, string> {
  return { ...UPLOAD_TYPE_TRANSLATIONS };
}
