export const TAGS = [
  // --- TIPOS DE INTERFAZ
  "HUD",
  "Mapa",
  "Menú principal",
  "Menú de pausa",
  "Inventario",
  "Misiones",
  "Diálogos",
  "Configuración",
  "Cinemáticas",
  "Pantalla de carga",

  // --- FUNCIONES
  "Barra de vida",
  "Minimapa",
  "Marcadores",
  "Lista de jugadores",
  "Logros",
  "Barra de experiencia",
  "Cooldowns",
  "Racha de muertes",
  "Misiones secundarias",
  "Quick slots",
  "Botones de acción",
  "Barra de habilidades",
  "Interfaz de sigilo",
  "Detección de enemigos",
  "Interfaz táctica",
  "Radar",
  "Subtítulos",
  "Árbol de decisiones",
  "Estadísticas del jugador",
  "Interfaz de viaje rápido",
  "Transición de zona",
  "Interfaz contextual",
  "Interfaz de escaneo",
  "Modo espectador",
  "Pantalla de muerte",
  "Diarios / notas",
  "Interfaz de eventos temporales",

  // --- ESTÉTICAS
  "Estilo medieval",
  "Estilo sci-fi",
  "Estilo steampunk",
  "Estilo cartoon",
  "Estilo pixel art",
  "Estilo low-poly",
  "Estética VHS",
  "UI transparente",
  "UI fragmentada",
  "UI sin texto",
  "Estilo 2D",
  "Estilo isométrico",
  "Estilo minimalista",
  "Estética retro",
  "Estilo futurista",

  // --- GÉNEROS
  "Shooter",
  "RPG",
  "MOBA",
  "Battle Royale",
  "Roguelike",
  "Metroidvania",
  "Plataformas",
  "Survival horror",
  "Simulador",
  "Estrategia en tiempo real",
  "Carreras",
  "Peleas",
  "Puzzle",
  "Terror",
  "Aventura gráfica",
  "Sandbox RPG",
  "Táctico por turnos",
  "Shooter táctico",
  "Hack and slash",
  "Beat 'em up",
  "Idle",
  "Builder",
  "Survival",
  "Exploración",
  "Tycoon",
  "Idle clicker",
  "City builder",
  "Tower defense",
  "Party game",
  "Deck builder",
  "Point and click",
  "Visual novel",
  "Match 3",
  "Auto battler",
  "Bullet hell",
  "Casual",
  "Drama interactivo",
  "Juego educativo",
  "Gestión de recursos",
  "Clicker incremental",
  "Farming sim",
  "Sandbox creativo",
  "Caza de monstruos",
  "Narrativa interactiva",
  "Juego rítmico",
  "Cocina",
  "Escape room",
  "Juego de cartas",
  "Musical",
  "Terror psicológico",
  "Rompecabezas lógico",
  "Construcción de bases",
  "Crafting",
  "Exploración espacial",
  "Mech combat",
  "Juegos de tablero",
  "Trading card game",
  "MMORPG",
  "FPS arena",
  "Shooter cooperativo",
  "Defensa de línea",
  "Wargame",
  "JRPG",
  "ARPG",
  "CRPG",
  "Builder táctico",
  "Idle RPG",

  // --- PLATAFORMAS / HARDWARE
  "PC",
  "PS5",
  "Xbox",
  "Switch",
  "Mobile",
  "VR",
  "Steam Deck",
  "Controles táctiles",
  "Joystick",
  "Mouse y teclado",

  // --- CONTEXTO Y AMBIENTE
  "Día y noche",
  "Interfaz de clima",
  "Inmersiva",
  "Minimalista",
  "Cinemática",
  "Multijugador",
  "Singleplayer",
  "Cooperativo",
  "Competitivo",
  "Sandbox",
  "Narrativo",
  "Open world",
  "Lineal",
  "First person",
  "Third person",
];

export const TAG_TRANSLATIONS: Record<string, string[]> = {
  // --- TIPOS DE INTERFAZ
  HUD: ["hud"],
  Mapa: ["map", "world map"],
  "Menú principal": ["main menu", "start screen"],
  "Menú de pausa": ["pause menu"],
  Inventario: ["inventory"],
  Misiones: ["quests", "missions", "objectives"],
  Diálogos: ["dialogues", "conversations"],
  Configuración: ["settings", "options menu"],
  Cinemáticas: ["cutscenes", "cinematics"],
  "Pantalla de carga": ["loading screen"],

  // --- FUNCIONES
  "Barra de vida": ["health bar"],
  Minimapa: ["minimap"],
  Marcadores: ["markers", "objectives"],
  "Lista de jugadores": ["player list", "scoreboard"],
  Logros: ["achievements"],
  "Barra de experiencia": ["experience bar", "xp bar"],
  Cooldowns: ["cooldowns", "skill timer"],
  "Racha de muertes": ["kill streak", "multikill"],
  "Misiones secundarias": ["side quests", "secondary missions"],
  "Quick slots": ["quick slots", "hotbar"],
  "Botones de acción": ["action buttons"],
  "Barra de habilidades": ["skill bar", "ability bar"],
  "Interfaz de sigilo": ["stealth UI", "stealth indicator"],
  "Detección de enemigos": ["enemy detection", "awareness meter"],
  "Interfaz táctica": ["tactical UI", "strategy overlay"],
  Radar: ["radar", "scanner"],
  Subtítulos: ["subtitles", "captions"],
  "Árbol de decisiones": ["decision tree", "choice wheel"],
  "Estadísticas del jugador": ["player stats", "character stats"],
  "Interfaz de viaje rápido": ["fast travel", "travel map"],
  "Transición de zona": ["zone transition", "area change"],
  "Interfaz contextual": ["contextual UI", "adaptive interface"],
  "Interfaz de escaneo": ["scan interface", "scanner UI"],
  "Modo espectador": ["spectator mode", "viewer mode"],
  "Pantalla de muerte": ["death screen", "you died"],
  "Diarios / notas": ["journals", "notes", "lore entries"],
  "Interfaz de eventos temporales": ["event UI", "limited-time event"],

  // --- ESTÉTICAS
  "Estilo medieval": ["medieval"],
  "Estilo sci-fi": ["sci-fi", "science fiction", "futuristic"],
  "Estilo steampunk": ["steampunk"],
  "Estilo cartoon": ["cartoon", "cel shaded"],
  "Estilo pixel art": ["pixel art"],
  "Estilo low-poly": ["low poly"],
  "Estética VHS": ["vhs", "retro filter"],
  "UI transparente": ["transparent UI"],
  "UI fragmentada": ["fragmented UI", "glitch"],
  "UI sin texto": ["textless UI", "icon-only interface"],
  "Estilo 2D": ["2d"],
  "Estilo isométrico": ["isometric"],
  "Estilo minimalista": ["minimalist"],
  "Estética retro": ["retro", "nostalgic"],
  "Estilo futurista": ["futuristic", "hi-tech"],

  // --- GÉNEROS
  Shooter: ["shooter", "fps", "tps"],
  RPG: ["rpg", "role-playing"],
  MOBA: ["moba"],
  "Battle Royale": ["battle royale"],
  Roguelike: ["roguelike", "roguelite"],
  Metroidvania: ["metroidvania"],
  Plataformas: ["platformer", "jump and run"],
  "Survival horror": ["survival horror"],
  Simulador: ["simulator", "simulation"],
  "Estrategia en tiempo real": ["real-time strategy", "rts"],
  Carreras: ["racing"],
  Peleas: ["fighting", "brawler"],
  Puzzle: ["puzzle"],
  Terror: ["horror"],
  "Aventura gráfica": ["graphic adventure", "point and click"],
  "Sandbox RPG": [
    "sandbox rpg",
    "open world rpg",
    "rpg sandbox",
    "open world role playing",
    "open-ended rpg",
  ],
  "Táctico por turnos": [
    "turn-based strategy",
    "tactical rpg",
    "turn-based tactics",
  ],
  "Shooter táctico": ["tactical shooter"],
  "Hack and slash": ["hack and slash", "slasher"],
  "Beat 'em up": ["beat 'em up", "brawler"],
  Idle: ["idle", "afk game"],
  Builder: ["builder", "construction simulator"],
  Survival: [
    "survival",
    "crafting survival",
    "open world survival",
    "zombie survival",
    "survival game",
  ],
  Exploración: ["exploration", "open world", "free roam", "explore vast world"],
  Tycoon: ["tycoon", "management sim"],
  "Idle clicker": ["idle clicker", "incremental game"],
  "City builder": ["city builder", "city sim"],
  "Tower defense": ["tower defense", "td"],
  "Party game": ["party game", "multiplayer mini games"],
  "Deck builder": ["deck builder", "card strategy"],
  "Point and click": ["point and click", "mouse adventure"],
  "Visual novel": ["visual novel", "interactive story"],
  "Match 3": ["match-3", "tile matching"],
  "Auto battler": ["auto battler", "auto chess"],
  "Bullet hell": ["bullet hell", "danmaku"],
  Casual: ["casual"],
  "Drama interactivo": ["interactive drama", "narrative experience"],
  "Juego educativo": ["educational game", "learning game"],
  "Gestión de recursos": ["resource management", "economy sim"],
  "Clicker incremental": ["clicker", "incremental"],
  "Farming sim": ["farming simulator", "farm game"],
  "Sandbox creativo": ["creative sandbox", "building sandbox"],
  "Caza de monstruos": ["monster hunter", "creature hunting"],
  "Narrativa interactiva": ["interactive narrative", "story driven"],
  "Juego rítmico": ["rhythm game", "music game"],
  Cocina: ["cooking", "chef game"],
  "Escape room": ["escape room", "puzzle escape"],
  "Juego de cartas": ["card game"],
  Musical: ["musical", "music game"],
  "Terror psicológico": ["psychological horror"],
  "Rompecabezas lógico": ["logic puzzle", "brain teaser"],
  "Construcción de bases": ["base building", "base management"],
  Crafting: ["crafting", "item creation"],
  "Exploración espacial": ["space exploration", "space sim"],
  "Mech combat": ["mech combat", "mecha"],
  "Juegos de tablero": ["board game", "tabletop"],
  "Trading card game": ["trading card game", "tcg"],
  MMORPG: ["mmorpg", "massively multiplayer rpg"],
  "FPS arena": ["arena shooter", "fast-paced fps"],
  "Shooter cooperativo": ["co-op shooter", "team shooter"],
  "Defensa de línea": ["lane defense", "line defense"],
  Wargame: ["wargame", "military sim"],
  JRPG: ["jrpg", "japanese rpg"],
  ARPG: ["action rpg", "arpg", "combat rpg", "fast-paced rpg"],
  CRPG: ["crpg", "classic rpg"],
  "Builder táctico": ["tactical builder", "strategy construction"],
  "Idle RPG": ["idle rpg", "afk rpg"],

  // --- PLATAFORMAS / HARDWARE
  PC: ["pc"],
  PS5: ["playstation 5", "ps5"],
  Xbox: ["xbox"],
  Switch: ["switch", "nintendo switch"],
  Mobile: ["mobile", "android", "ios"],
  VR: ["vr", "virtual reality"],
  "Steam Deck": ["steam deck"],
  "Controles táctiles": ["touch controls", "touchscreen"],
  Joystick: ["joystick", "gamepad"],
  "Mouse y teclado": ["mouse and keyboard", "keyboard and mouse"],

  // --- CONTEXTO Y AMBIENTE
  "Día y noche": ["day and night", "dynamic lighting"],
  "Interfaz de clima": ["weather UI", "weather effects"],
  Inmersiva: ["immersive"],
  Minimalista: ["minimalist", "clean UI"],
  Cinemática: ["cinematic", "movie-like"],
  Multijugador: ["multiplayer"],
  Singleplayer: ["singleplayer"],
  Cooperativo: ["co-op", "cooperative"],
  Competitivo: ["competitive"],
  Sandbox: ["sandbox", "open gameplay"],
  Narrativo: ["narrative", "story-driven"],
  "Open world": ["open world"],
  Lineal: ["linear"],
  "First person": ["first-person", "fps view"],
  "Third person": ["third-person", "tps view"],
};
