import "./globals.css";

import AppFooter from "@/components/app-footer";
import AppHeader from "@/components/app-header";
import Providers from "@/components/providers";
import { dmSans } from "@/config/font.config";
import {
  getFilterOptions,
  getSearchSuggestions,
} from "@/db/querys/filter-querys";
import { cn } from "@/lib";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HUDLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const filterOptions = getFilterOptions();
  const suggestions = getSearchSuggestions();

  return (
    <html lang="es" suppressHydrationWarning>
      <body className={cn(dmSans.variable, "antialiased")}>
        <Providers>
          <AppHeader
            filterOptionsPromise={filterOptions}
            suggestionsPromise={suggestions}
          />
          {children}
          <AppFooter />
        </Providers>
      </body>
    </html>
  );
}
